name: Block Island Brands
favicon: null
layout_spectrum: 0.2461
typography_spectrum: 0.14644
title: "Products inspired by the natural surroundings of RI's Ocean Jewel."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f6f9'
    - '#e5cc00'
    - '#432e55'
    - '#bd398d'
    - '#eb8abd'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
