name: Block Island Brands
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35982
title: "Products inspired by the natural surroundings of RI's Ocean Jewel."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9bcc1'
    - '#782472'
    - '#6c5997'
    - '#64a06a'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
