name: Block Island Brands
favicon: null
layout_spectrum: 0.6372923017479479
typography_spectrum: 0.41822219151072204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5537494102027267
  lightness: 0.07348667574115098
  saturation: 0.11084745242260396
  rhythmicContrast: 0.46260540396906435
purpose: []
